#!/bin/sh
NAME=$1

if [ x$NAME = x ] ; then
echo "usage $0 <template_name>"
exit 1
fi

. ./builder_setup

rpmbuild --target noarch \
         --define "template_name $NAME" \
         --define "DIST $DIST" \
         --define "_topdir $PWD/rpmbuild" \
         --define "_tmppath $PWD/rpmbuild/tmp" \
         -bb templates.spec
