#!/bin/bash

# Setup env variables

case "$DIST" in
	fc*)
		DISTRIBUTION=fedora
		VERSION=${DIST/fc/}
		;;
	*)
		DISTRIBUTION="$DIST"
		VERSION=
		;;
esac

if [ -d "scripts_$DIST" ]; then
	SCRIPTSDIR="scripts_$DIST"
else
	SCRIPTSDIR="scripts_$DISTRIBUTION"
fi

CACHEDIR=cache_$DIST

export SCRIPTSDIR CACHEDIR
echo $DISTRIBUTION $VERSION
